config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :articles
  root "articles#index"
  #Users controller (Signup setup)
  resources :users
  get "/signup" => "users#new"
  
  #Sessions controller rutes (Login setup)
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#drestroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


	def author?
		self.role == "author"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  	helper_method :current_user

  	def current_user 
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	  def require_user 
	  redirect_to '/login' unless current_user 
	end

	def require_logged_out
		redirect_to "/" unless current_user == nil
	end

	def require_author
		redirect_to "/" unless 
		current_user.author?
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :require_user, only: [:show, :new, :edit]
	before_action :require_author, only: [:edit, :update, :destroy]
	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new 
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render "new"
		end
	end	

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render "edit"
		end

	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end

	private
	def article_params
		params.require(:article).permit(:title, :author, :body)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :require_logged_out, only: [:new]
	def new

	end

	def create
		@user = User.find_by_email(params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			redirect_to "/"
		else
			redirect_to "/login"
		end
	end

	def drestroy
		session[:user_id] = nil
		redirect_to "/"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_logged_out, only: [:new]
	before_action :require_user, only: [:show, :edit]

	def show
		@user = User.find(session[:user_id])
	end

	def new
		@user = User.new
	end

	def edit
		@user = User.find(session[:user_id])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to "/"
		else
			redirect_to "/signup"
		end
	end

	def update
		@user = User.find(session[:user_id])
		if @user.update(user_params)
			redirect_to @user
		else
			render "edit"
		end
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :role, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="update-article">
  <div class="container">

    <%= form_for(@article) do |f| %>    
      <%= f.text_field :title %>
      <%= f.text_field :author %>
      <%= f.text_area :body %>

      <%= f.submit "Save", :class => "btn-submit" %>
    <% end %>

  </div>
</div>

app/views/articles/index.html.erb
<div class="articles">
  <div class="container">
    
    <% @articles.each do |article| %>
    <div class="article">
      <p class="date"><%= article.created_at.strftime('%b %d') %></p>
      <!-- http://stackoverflow.com/questions/1086360/how-do-i-wrap-link-to-around-some-html-ruby-code -->
      <%= link_to(article) do %>
        <h2><%= article.title %></h2>
      <% end %>
      <p class="author">by <%= article.author %></p>
      <p class="article_content"><%= truncate(article.body , :length => 140) %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="new-article">
  <div class="container">

    <%= form_for(@article) do |f| %>    
      <%= f.text_field :title, :placeholder => "Title" %>
      <%= f.text_field :author, :placeholder => "Author" %>
      <%= f.text_area :body %>

      <%= f.submit "Save" %>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="article">
  <div class="container">
    <p class="date"><%= @article.created_at.strftime('%b %d') %></p>
    <h2><%= @article.title %></h2>
    <p class="author">by <%= @article.author %></p>
    <p class="article_content"><%= @article.body %></p>

    <!-- Your code here -->

    <% if current_user && current_user.author? %> 
		  <p class="article-edit"> 
		    <%= link_to "Edit article", edit_article_path(@article.id) %> 
		  </p> 
		  <p class="article-edit"> 
		    <%= link_to "Delete article", article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %> 
		  </p> 
		<% end %>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newstand</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:300,700,100,400' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="header">
      <div class="container">
        <%= link_to(root_path) do %>
          <h1><span class="dark">n</span>ewstand</h1>
        <% end %>

        <div class="nav">
          
          <!-- Your code here -->
					<% if current_user %> 
            <ul> 
              <%= link_to user_path(:id), class: "user-pro" do %>
                <li><%= current_user.first_name + " " + current_user.last_name %></li> 
              <% end %>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
            </ul> 
          <% else %> 
            <ul> 
              <li><%= link_to "Login", 'login' %></a></li> 
              <li><%= link_to "Signup", 'signup' %></a></li>
            </ul> 
          <% end %>

        </div>
      </div>
    </div>


    <%= yield %>

  </body>
</html>

app/views/users/edit.html.erb
<div class="signup">
  <div class="container">
    
    <!-- Your form here -->
		<%= form_for :user, url: user_path(@user), method: :patch do |f| %>
			<%= f.label :image %>
			<%= f.file_field :image %>
			<%= f.text_field :first_name, :placeholder => "First name" %>
			<%= f.text_field :last_name, :placeholder => "Last name" %>
			<%= f.email_field :email, :placeholder => "Email" %>
			<%= f.password_field :password, :placeholder => "Password" %>
			<%= f.submit "Update profile", class: "btn-submit" %>
		<% end %>
		<%= link_to "Back", user_path(:id), class: "user-edit" %>
  </div>
</div>

app/views/users/new.html.erb
<div class="signup">
  <div class="container">
    
    <!-- Your form here -->
		<%= form_for @user, html: { multipart: true } do |f| %>
			<%= f.label :image %>
			<%= f.file_field :image %>
			<%= f.text_field :first_name, :placeholder => "First name" %>
			<%= f.text_field :last_name, :placeholder => "Last name" %>
			<%= f.email_field :email, :placeholder => "Email" %>
			<%= f.text_field :role, :placeholder => "Role" %>
			<%= f.password_field :password, :placeholder => "Password" %>
			<%= f.submit "Create an account", class: "btn-submit" %>
		<% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="article">
	<%= image_tag @user.image.url(:medium), class: "profile-img" %>
	<h1><%= "Name: " + current_user.first_name %></h1>
	<h1><%= "Las Name: " + current_user.last_name %></h1>
	<h1><%= "Email: " + current_user.email %></h1>	
	<%= link_to "Edit", edit_user_path(:id), class: "user-edit" %>
	<%= link_to "New article", new_article_path, class: "user-edit" %>
</div>